cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    #url(r'^login/$', views.login, name='login'),
    #url(r'^logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    #re_path(r'^accounts/login/$', LoginView.as_view(template_name='regiatration/login.html'), name="login"),
    #re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import logout, password_change as pwd_change, password_change_done as pwd_change_done, password_reset as reset, password_reset_done as reset_done, password_reset_confirm as reset_confirm, password_reset_complete as reset_complete
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    #url(r'^logout/$', logout, name='logout'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    url(r'^register/$', views.register, name='register'),
    #url(r'^register_done/$', views., name='register'),
    # change password urls
    #url(r'^password-change/$', pwd_change, name='password_change'),
    url(r'^password-change/done/$', pwd_change_done, name='password_change_done'),
   # url(r'^password-change/$', pwd_change, {'post_change_redirect': '/password-change/done/'}, name='password_change'),
    url(r'^password-change/$', pwd_change, {'post_change_redirect': '/password-change/done/'}, name='password_change'),
# restore password urls
    url(r'^password-reset/complete/$', reset_complete, name='password_reset_complete'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', reset_confirm, {'post_reset_redirect': '/password-reset/complete/'}, name='password_reset_confirm'),
    url(r'^password-reset/done/$', reset_done, name='password_reset_done'),
    url(r'^password-reset/$', reset, {'post_reset_redirect': '/password-reset/done/', 'email_template_name': 'registration/password_reset_email.html'}, name='password_reset'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

shop/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType




SIZE_CHOICES = [(j, str(j)) for j in ['XS','S','M','L','XL','XXL']]
COLOR_CHOICES = [(k, str(k)) for k in ['Green','Blue','Red','Orange','Yellow','Black','White']]

#COLOR_CHOICES = (
    #('Green','GREEN'),
    #('Blue','BLUE'),
    #('Red','RED'),
    #('Orange','ORANGE'),
    #('Black','BLACK'),
    #('Yellow','YELLOW'),
    #('White','WHITE')
#)
#SIZE_CHOICES = (
    #('XS','XS'),
    #('S','S'),
    #('M','M'),
    #('L','L'),
    #('XL','XL'),
    #('XXL','XXL')
#)
class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    #image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    image = models.CharField(max_length=510, default="https://i.ibb.co/1fw5QMB/default-image.jpg" , null=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    size = models.CharField(max_length=6, choices=SIZE_CHOICES, default='L')
    color = models.CharField(max_length=20, choices=COLOR_CHOICES, default='green')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail',
                           args=[self.id, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Product,on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class CommentForm(forms.ModelForm):
    class Meta:
        model =Comment
        fields = ('name', 'email', 'body')

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from .forms import *
from .models import Category, Product
from .models import Product, Comment
from .forms import CommentForm
from cart.forms import CartAddProductForm
#from .recommender import Recommender
from django.db.models import Q


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
            user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'shop/register_done.html', {'new_user': new_user})
    else:
      user_form = UserRegistrationForm()
      return render(request, 'shop/register.html', {'user_form': user_form})


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    query = request.GET.get('q')
    if query:
        products = products.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)

    cart_product_form = CartAddProductForm()

    # List of active comments for this post
    comments = product.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = product
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request,
                      'shop/product/detail.html',
                      {'product': product,
                       'comments': comments,
                       'new_comment': new_comment,
                       'comment_form': comment_form,
                       'cart_product_form': cart_product_form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


def about(request):
 return render(request,'shop/about.html',{})


def contact(request):
 return render(request,'shop/contact.html',{})

shop/templates/shop/about.html
<div class="nav">
    {% extends "shop/base.html" %}
</div>
{% load static %}
<!DOCTYPE html>
<html>
{% block content %}
<head>
<style>

body {
  font-family: 'Lobster', cursive;
  font-size: 17px;
}

.container {
  position: relative;
  max-width: 1000px;
  margin: 0 auto;
}

.container img {vertical-align: middle;}

.container .contents {
  position: absolute;
  bottom: 0;
  background: rgb(0, 0, 0); /* Fallback color */
  background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
  color: #f1f1f1;
  width: 100%;
  padding: 0px;
}
</style>
</head>
<body>

<h2>Help Us get you a fashionable look ever!!</h2>

<div class="container">
  <img src="https://i.ibb.co/pz7YK6R/apparel.jpg" alt="apparel" style="width:100%;">
  <div class="contents">
    <h1> V5 Stores</h1>
    <p> If your are in search of trying to change your look, Yes you are in the right place!!V5Store helps you select the
        desired outfit.V5Store’s, Inc. is one of the nation’s premier retailers started in 2017.
        V5Store’s, Inc. operates stores in 44 states, the District of Columbia, Guam and Puerto Rico.
        V5Store’s, Inc. has corporate offices in Omaha. Prior to June 1, 2017, V5Store’s, Inc. was known as V5apparel store. </p>
  </div>
</div>

</body>
{% endblock %}
</html>

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title><h3>{% block title %}V5 Clothing</h3>{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
 <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
</head>
<body>
  <div id="subheader">
  <ul id="ul li">
      <li><a class="navbar-brand"  href="{% url "shop:product_list" %}"><img width="50px" src="{% static 'img/V5Logo.png' %}"> </a> <span><a class="logo" href="{% url "shop:product_list" %}">V5 Clothing</a></span></li>

           <li> <form action="" method="GET" accept-charset="utf-8">
		<input name="q" type="text" placeholder="Search Products" style="width: 500px "  value= "{{ request.GET.q }}" id="search_prod"/>
			<input type="submit"  value="Search" class="btn" />
	</form></li>
    <li><div class="cart">
      {% with total_items=cart|length %}
          {% if cart|length > 0 %}
            <img alt="Your cart" width="25" height="25" src="{% static 'img/cart.png' %}"/>
            <a href="{% url "cart:cart_detail" %}">
              {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_total_price }}
            </a>
          {% else %}
            <img alt="Your cart" width="25" height="25" src="{% static 'img/cart.png' %}">
          {% endif %}</div></li>
         <li>
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            <li><a href="{% url 'shop:password_change' %}"><i class="fa fa-btn fa-sign-out"></i>Change Password</a></li>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a href="{% url 'shop:register' %}"><i class="glyphicon glyphicon-log-in"></i>SignUp</a></li>
                {% endif %}
         {% endwith %} </ul>
          <ul id="ul li2" >
          <li2>
          <a href="{% url "shop:product_list" %}">Home</a>
          </li2>

          {% for c in categories %}
        <li2 {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li2>
      {% endfor %}
   <li2 ><a href="{% url "shop:about" %}">About Us</a></li2>
               <li2><a href="{% url "shop:contact" %}">Contact Us</a></li2>
                <li2><a href="{% url "shop:product_list" %}">Special Deals</a></li2>
      </li2>
    </ul>
    </div>
  <div id="content">
    {% block content %}

    {% endblock %}
  </div>
   <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.js' %}"></script>
</body>
</html>

shop/templates/shop/contact.html
<div class="nav">
    {% extends "shop/base.html" %}
</div>
{% load static %}
<!DOCTYPE html>
<html>
{% block content %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
    height: 100%;
}
h1, h2, h3, h4 {
    font-family: 'Lobster', cursive;
}
.parallax {
    /* The image used */



    /* Full height */
    height: 100%;

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}

/* Turn off parallax scrolling for tablets and phones. Increase the pixels if needed */
@media only screen and (max-device-width: 1366px) {
    .parallax {
        background-attachment: scroll;
    }
}
</style>
</head>
<body>

<h1><p align="center">Feel free to get in touch with us!!</p></h1>


<h2><p align="center">Have Questions about your orders ??</p></h2>
<h2><p align="center">Give us a call @ +17323258641</p></h2>
<h2><p align="center">or</p></h2>
<h2><p align="center">Shoot us a mail to v5storein@gmail.com</p></h2>
<h2><p align="center">will shall get back to you on the same day!!</p></h2>
<div>

   <h2> <p  style="color:black;"  style="width:40px;height:40px;" align="center"> Catch us@  any of the following </p></h2>
   <p align="center"> <a href="http://twitter.com"> <img src="https://i.ibb.co/H2sGqVx/twitter.png" width="100" height="100"></a> <a href="mailto:{{ site.email }}"><img src="https://i.ibb.co/NNmbg8w/email.png" width="100" height="100"></a>  <a href="https://www.facebook.com"> <img src="https://i.ibb.co/B6L94Ds/facebook.png" width="100" height="100"></a> <a href="https://www.instagram.com"> <img src="https://i.ibb.co/grngR1L/instagram.png" width="100" height="100"></a>
</div>

<div class="parallax"></div>

</body>
{% endblock %}
</html>

shop/templates/shop/register.html
{% extends "shop/base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an account</h1>


    <p>Please, sign up using the following form:</p>
    <form action="{% url 'shop:register' %}" method="post" >
    {{ user_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Create my account"></p>
    </form>
{% endblock %}

shop/templates/shop/register_done.html
{% extends "shop/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>

    <p>Your account has been successfully created. Now you can <a href="{% url "login" %}">log in</a>.</p>
{% endblock %}