cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    #url(r'^login/$', views.login, name='login'),
    #url(r'^logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    #re_path(r'^accounts/login/$', LoginView.as_view(template_name='regiatration/login.html'), name="login"),
    #re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order/<int:order_id>/', views.cust_order, name='cust_order_detail'),
    path('order/<int:order_id>/pdf', views.cust_order_pdf, name='cust_order_pdf'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/(<int:order_id>)/pdf',  views.admin_order_pdf, name='admin_order_pdf'),

    #url(r'^admin/order/(?P<order_id>\d+)/pdf/$',  views.admin_order_pdf, name='admin_order_pdf'),
]

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('done/', views.payment_done, name='done'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('order/<int:order_id>/', views.cust_order_detail, name='cust_order_detail'),
    path('order/<int:order_id>/pdf', views.cust_order_pdf, name='cust_order_pdf')
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import braintree
from django.shortcuts import render, redirect, get_object_or_404
from orders.models import Order
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings
#import weasyprint
from io import BytesIO
from django.urls import reverse
from django.utils.safestring import mark_safe

def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        # retrieve nonce
        nonce = request.POST.get('payment_method_nonce', None)
        # create and submit transaction
        result = braintree.Transaction.sale({
            'amount': '{:.2f}'.format(order.get_total_cost()),
            'payment_method_nonce': nonce,
            'options': {
                'submit_for_settlement': True
            }
        })
        if result.is_success:
            # mark the order as paid
            order.paid = True
            # store the unique transaction id
            order.braintree_id = result.transaction.id
            order.save()

            # create invoice e-mail
            #subject = 'My Shop - Invoice no. {}'.format(order.id)
            #message = 'Please, find attached the invoice for your recent purchase.'
            #email = EmailMessage(subject,
             #                    message,
             #                  'admin@myshop.com',
              #                   [order.email])

            # generate PDF
            #html = render_to_string('orders/order/pdf.html', {'order': order})
            #out = BytesIO()
            #stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + 'css/pdf.css')]
            #weasyprint.HTML(string=html).write_pdf(out,
               #                                    stylesheets=stylesheets)
            # attach PDF file
            #email.attach('order_{}.pdf'.format(order.id),
             #            out.getvalue(),
              #           'application/pdf')
            # send e-mail
            #email.send()

            return redirect('payment:done')
        else:
            return redirect('payment:canceled')
    else:
        # generate token
        client_token = braintree.ClientToken.generate()
        return render(request,
                      'payment/process.html',
                      {'order': order,
                       'client_token': client_token})


def payment_done(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'payment/done.html',{'order': order})


def payment_canceled(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'payment/canceled.html',{'order': order})

def cust_order_detail(obj):
    return mark_safe('<a href="{}">View</a>'.format(
        reverse('orders:cust_order_detail', args=[obj.id])))

def cust_order_pdf(obj):
    return '<a href="{}">PDF</a>'.format(
        reverse('orders:cust_order_pdf', args=[obj.id]))
cust_order_pdf.allow_tags = True
cust_order_pdf.short_description = 'PDF bill'

payment/templates/payment/canceled.html
{% extends "shop/base.html" %}

{% block content %}
  <h1>Your payment has not been processed</h1>
  <p>There was a problem processing your payment.</p>
<h1>Order {{ order.id }}</h1>
<ul class="object-tools">
  <li>
    <a href="#" onclick="window.print();">Print order</a>
  </li>
</ul>
<table>
  <tr>
    <th>Created</th>
    <td>{{ order.created }}</td>
  </tr>
  <tr>
    <th>Customer</th>
    <td>{{ order.first_name }} {{ order.last_name }}</td>
  </tr>
  <tr>
    <th>E-mail</th>
    <td><a href="mailto:{{ order.email }}">{{ order.email }}</a></td>
  </tr>
  <tr>
    <th>Address</th>
    <td>{{ order.address }}, {{ order.postal_code }} {{ order.city }}</td>
  </tr>
  <tr>
    <th>Total amount</th>
    <td>${{ order.get_total_cost|floatformat:"2" }}</td>
  </tr>
  <tr>
    <th>Status</th>
    <td>{% if order.paid %}Paid{% else %}Pending payment{% endif %}</td>
  </tr>
</table>

<div class="module">
  <h2>Items bought</h2>
  <div class="tabular">
    <table style="width:100%">
      <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Size</th>
            <th>Color</th>
            <th>Total</th>
        </tr>
      </thead>
      <tbody>
        {% for item in order.items.all %}
          <tr class="row{% cycle "1" "2" %}">
            <td>{{ item.product.name }}</td>
            <td class="num">${{ item.price }}</td>
            <td class="num">{{ item.quantity }}</td>
            <td class="num">${{ item.get_cost }}</td>
            <td>{{ item.size }}</td>
            <td>{{ item.color }}</td>
          </tr>
        {% endfor %}
        <tr class="total">
          <td colspan="5">Total price after discount</td>
          <td class="num">${{ order.get_total_cost|floatformat:"2" }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

payment/templates/payment/done.html
{% extends "shop/base.html" %}

{% block content %}
  <h1>Your payment was successful</h1>
  <p>Your payment has been processed successfully.</p>
<h1>Order {{ order.id }}</h1>
<ul class="object-tools">
  <li>
    <a href="{% url 'orders:admin_order_pdf' order_id=order.id %}">Print order</a>
  </li>
</ul>
<table>
  <tr>
    <th>Created</th>
    <td>{{ order.created }}</td>
  </tr>
  <tr>
    <th>Customer</th>
    <td>{{ order.first_name }} {{ order.last_name }}</td>
  </tr>
  <tr>
    <th>E-mail</th>
    <td><a href="mailto:{{ order.email }}">{{ order.email }}</a></td>
  </tr>
  <tr>
    <th>Address</th>
    <td>{{ order.address }}, {{ order.postal_code }} {{ order.city }}</td>
  </tr>
  <tr>
    <th>Total amount</th>
    <td>${{ order.get_total_cost|floatformat:"2" }}</td>
  </tr>
  <tr>
    <th>Status</th>
    <td>{% if order.paid %}Paid{% else %}Pending payment{% endif %}</td>
  </tr>
</table>

<div class="module">
  <h2>Items bought</h2>
  <div class="tabular">
    <table style="width:100%">
      <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
      </thead>
      <tbody>
        {% for item in order.items.all %}
          <tr class="row{% cycle "1" "2" %}">
            <td>{{ item.product.name }}</td>
            <td>${{ item.price }}</td>
            <td>{{ item.quantity }}</td>
            <td>${{ item.get_cost }}</td>
          </tr>
        {% endfor %}
        <tr class="total">
          <td colspan="3">Total price after discount</td>
          <td>${{ order.get_total_cost|floatformat:"2" }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}

{% block title %}Pay by credit card{% endblock %}

{% block content %}

<div style="float: left; width: 50%">
  <h1>Pay by credit card</h1>
  <form action="." id="payment" method="post">

    <label for="card-number">Card Number</label>
    <div id="card-number" class="field"></div>

    <label for="cvv">CVV</label>
    <div id="cvv" class="field"></div>

    <label for="expiration-date">Expiration Date</label>
    <div id="expiration-date" class="field"></div>

    <input type="hidden" id="nonce" name="payment_method_nonce" value="">
    {% csrf_token %}
    <input type="submit" value="Pay">
  </form>
  </div>
<div style="float: left; width: 50%">
  <h1>Pay with PayPal</h1>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <input type="hidden" name="cmd" value="_xclick">
    <input type="hidden" name="business" value="v5storein@gmail.com">
    <input type="hidden" name="lc" value="US">
    <input type="hidden" name="button_subtype" value="services">
    <input type="hidden" name="currency_code" value="USD">
    <input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynowCC_LG.gif:NonHosted">
    <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
    <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>


</div>
  <!-- Load the required client component. -->
  <script src="https://js.braintreegateway.com/web/3.29.0/js/client.min.js"></script>
  <!-- Load Hosted Fields component. -->
  <script src="https://js.braintreegateway.com/web/3.29.0/js/hosted-fields.min.js"></script>
  <script>
    var form = document.querySelector('#payment');
    var submit = document.querySelector('input[type="submit"]');
    braintree.client.create({
      authorization: '{{ client_token }}'
    }, function (clientErr, clientInstance) {
      if (clientErr) {
        console.error(clientErr);
        return;
      }
      braintree.hostedFields.create({
        client: clientInstance,
        styles: {
          'input': {'font-size': '13px'},
          'input.invalid': {'color': 'red'},
          'input.valid': {'color': 'green'}
        },
        fields: {
          number: {selector: '#card-number'},
          cvv: {selector: '#cvv'},
          expirationDate: {selector: '#expiration-date'}
        }
      }, function (hostedFieldsErr, hostedFieldsInstance) {
        if (hostedFieldsErr) {
          console.error(hostedFieldsErr);
          return;
        }
        submit.removeAttribute('disabled');
        form.addEventListener('submit', function (event) {
          event.preventDefault();
          hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
            if (tokenizeErr) {
              console.error(tokenizeErr);
              return;
            }
            // set nonce to send to the server
            document.getElementById('nonce').value = payload.nonce;
            // submit form
            document.getElementById('payment').submit();
          });
        }, false);
      });
    });
  </script>
{% endblock %}